version: "3.7"

services:
  oteldemo:
    build:
      context: ../
    environment:
      LEAD_DB_HOST: db:5432
      LEAD_JAEGER_REPORTER_URI: http://jaeger:14268/api/traces
      LEAD_JAEGER_SERVICE_NAME: leads-api
    ports:
      - 3000:3000
    depends_on:
      - db
      - jaeger
    networks:
      - otel-demo

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: leeds
      POSTGRES_USER: leedsvc
      POSTGRES_PASSWORD: leedsvc
    ports:
      - 5432:5432
    networks:
      - otel-demo

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      - "14268:14268"
    networks:
      - otel-demo

networks:
  otel-demo:
